#ifndef EVENTS_H
#define EVENTS_H

// used for initialisation of an event variable
typedef enum {
    E_NO,
    E_START,
    E_CONTINUE,
    E_INIT_PLANT,
    E_PASS_TIME,
    E_LIGHT_TOGGLE,
    E_HEATER_TOGGLE,
    E_WATER_PLANT,
    E_ASK_USER_INPUT,
    E_INCREASE_TIME,
    E_NON_VALID_INPUT,
    E_HELP,
    E_UPDATE,
    E_SERVICE,
    E_ADD_PLANT,
    E_CHANGE_PLANT,
    E_PUMP_TOGGLE,
    E_USER
} event_e;
/*
typedef enum {
    E_NO,
    E_START,
    E_CONTINUE,
    E_WATER_PLANT_LOW,
    E_WATERING_INTERFALL,
    E_WATERING,
    E_TEMP_OVER_MAX,
    E_TEMP_OVER_MIN,
    E_TEMP_ADJUST,
    E_LIGHT_TOGGLE,
    E_SERVICE_MODE,
    E_SERVICE_MODE_OFF,
    E_SELLECT_ACTIVE_PLANT,
    E_SET_ACTIVE_PLANT,
    E_WATER_CONTROL_ON,
    E_WATER_CONTROL_OFF,
    E_HEATER_TOGGLE,
    E_ADD_NEW_PLANT,
    E_SET_PLANT_NAME,
    E_SET_WATER_LEVEL,
    E_SET_LIGHT_HOURS,
    E_SET_MIN_TEMP,
    E_SET_MAX_TEMP,
    E_NON_VALID_VALUE,
    E_SAVE_NEW_PLANT
} event_e*/

#endif // EVENTS_H
