@startuml

title Tomato - The Automatic Greenhouse

[*] --> Initialised : E_START / TAGinitialise()
Initialised --> CheckForEvent : E_CONTINEU

CheckForEvent --> CheckForEvent : E_PASS_TIME
CheckForEvent --> CheckForEvent : E_LIGHT_TOGGLE
CheckForEvent --> CheckForEvent : E_HEATER_TOGGLE
CheckForEvent --> CheckForEvent : E_WATER_PLANT
CheckForEvent --> HandleUserInput : E_ASK_USER_INPUT

HandleUserInput --> HandleUserInput : E_NON_VALID_INPUT
HandleUserInput --> HandleUserInput : E_HELP
HandleUserInput --> HandleUserInput : E_UPDATE
HandleUserInput --> CheckForEvent : E_INCREASE_TIME
HandleUserInput --> HandleServiceInput : E_SERVICE

HandleServiceInput --> HandleServiceInput : E_ADD_PLANT
HandleServiceInput --> HandleServiceInput : E_CHANGE_PLANT
HandleServiceInput --> HandleServiceInput : E_PUMP_TOGGLE
HandleServiceInput --> HandleServiceInput : E_HEATER_TOGGLE
HandleServiceInput --> HandleServiceInput : E_LIGHT_TOGGLE
HandleServiceInput --> HandleServiceInput : E_NON_VALID_INPUT
HandleServiceInput --> CheckForEvent : E_USER


note left of CheckForEvent
	Checks are in this order:
    Light, heater, water
    Pass time
end note

@enduml