@startuml

title Tomato - The Automatic Greenhouse

[*] --> Initialised
Initialised : DSPinitialise();
Initialised : PTinitialise();
Initialised : FSMinitialise();
Initialised : LTinitialise();
Initialised : LCinitialise();
Initialised : TCinitialise();
Initialised : WCinitialise();
Initialised --> WaitForEvent
WaitForEvent --> WaitForEvent : non valid input

WaitForEvent --> LightToggle : check lighthours
LightToggle --> WaitForEvent

WaitForEvent --> HeaterToggle : check temperature
HeaterToggle --> WaitForEvent

WaitForEvent --> WaterPlant : check plant water level
WaterPlant --> WaitForEvent

WaitForEvent --> ServiceMode
ServiceMode --> WaitForEvent
ServiceMode --> ServiceMode : non valid input

ServiceMode --> LightToggle
LightToggle --> ServiceMode

ServiceMode --> HeaterToggle
HeaterToggle --> ServiceMode

ServiceMode --> PumpToggle
PumpToggle --> ServiceMode

ServiceMode --> ChangePlant
ChangePlant --> ServiceMode
ChangePlant --> ChangePlant : non valid input

ServiceMode --> NewPlant
NewPlant : char name[10]
NewPlant : int maxTemp
NewPlant : int minTemp
NewPlant : int maxWater
NewPlant : int lightHours
NewPlant --> ServiceMode
NewPlant --> NewPlant : non valid input

@enduml
